# Railway Nixpacks Configuration
# Instala Node.js e .NET SDK automaticamente

[phases.setup]
nixPkgs = ["nodejs_20", "dotnet-sdk_8"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build",
  "mkdir -p dist/templates",
  "cp -r src/templates/* dist/templates/"
]

[start]
cmd = "npm start"
