# Railway Nixpacks Configuration
# Instala Node.js e .NET SDK automaticamente

[phases.setup]
nixPkgs = ["nodejs_20", "dotnet-sdk_8"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"
